// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Donton.DataAccess.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Donton.DataAccess.Contexts
{
    public partial class DontonContext
    {
        private IDontonContextProcedures _procedures;

        public virtual IDontonContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new DontonContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IDontonContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<spContactListResult>().HasNoKey().ToView(null);
        }
    }

    public partial class DontonContextProcedures : IDontonContextProcedures
    {
        private readonly DontonContext _context;

        public DontonContextProcedures(DontonContext context)
        {
            _context = context;
        }

        public virtual async Task<List<spContactListResult>> spContactListAsync(long? UserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "UserId",
                    Value = UserId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<spContactListResult>("EXEC @returnValue = [dbo].[spContactList] @UserId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
