// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Donton.DataAccess.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Donton.DataAccess.Contexts
{
    public partial interface IDontonContextProcedures
    {
        Task<List<spContactListResult>> spContactListAsync(long? UserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
